sudo: requied
language: java
services:
  - docker

before_install:
  - mvn package
  - docker build -t mokassem/palindrome-message-checker .
script:
  - docker run -p9000:4567 mokassem/palindrome-message-checker
  - docker ps --all
