sudo: requied
language: java
services:
  - docker

before_install:
  - mvn package
  - docker build -t mokassem/palindrome-message-checker .
  - docker ps --all

script:
  - docker run -p127.0.0.1:80:4567 mokassem/palindrome-message-checker
